from turtle import Turtle
from turtle import Screen

def draw_snowman():

	turtle = Turtle()
	screen = Screen()

	turtle.hideturtle()
	turtle.penup()
	turtle.setposition((230, 10))
	turtle.pendown()
	turtle.color(("lightblue"), ("azure"))
	turtle.begin_fill()
	turtle.circle(26)
	turtle.penup()
	turtle.setposition((230, 62))
	turtle.pendown()
	turtle.circle(13)
	turtle.penup()
	turtle.setposition((230, 88))
	turtle.pendown()
	turtle.circle(8)
	turtle.end_fill()
	turtle.penup()
	#draw face and buttons
	turtle.setposition((228, 95))
	turtle.pendown()
	turtle.dot(2, "black")
	turtle.penup()
	turtle.setposition((234, 95))
	turtle.pendown()
	turtle.dot(2, "black")
	turtle.penup()
	turtle.setposition((230, 92))
	turtle.pendown()
	turtle.dot(3, "orange")
	turtle.penup()
	turtle.setposition((230, 70))
	turtle.pendown()
	turtle.dot(4, "black")
	turtle.penup()
	turtle.setposition((230, 80))
	turtle.pendown()
	turtle.dot(4, "black")
	turtle.penup()
	turtle.setposition((230, 50))
	turtle.pendown()
	turtle.dot(6, "black")
	turtle.penup()
	turtle.setposition((230, 40))
	turtle.pendown()
	turtle.dot(6, "black")
	turtle.penup()
	turtle.setposition((230, 30))
	turtle.pendown()
	turtle.dot(6, "black")

	#Draw hat

	turtle.penup()
	turtle.setposition((225, 100))
	turtle.pendown()
	turtle.color("blue")
	turtle.begin_fill()
	turtle.forward(10)
	turtle.left(90)
	turtle.forward(8)
	turtle.left(90)
	turtle.forward(10)
	turtle.left(90)
	turtle.forward(8)
	turtle.end_fill()

