from turtle import Turtle
from turtle import Screen

def christmas_tree():
    
    turtle = Turtle()
    screen = Screen()
    screen.colormode(255)

    turtle.hideturtle()
    turtle.penup()
    turtle.setposition((20, 20))
    turtle.begin_fill()
    turtle.pendown()
    turtle.color((15, 140, 15), (15, 225, 15))
    turtle.forward(25)
    turtle.left(150)
    turtle.forward(20)
    turtle.right(150)
    turtle.forward(15)
    turtle.left(150)
    turtle.forward(20)
    turtle.right(150)
    turtle.forward(10)
    turtle.left(150)
    turtle.forward(20)
    turtle.left(60)
    turtle.forward(20)
    turtle.left(150)
    turtle.forward(10)
    turtle.right(150)
    turtle.forward(20)
    turtle.left(150)
    turtle.forward(15)
    turtle.right(150)
    turtle.forward(20)
    turtle.left(150)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(4)
    turtle.left(90)
    turtle.forward(15)
    turtle.penup()
    turtle.end_fill()